#! /usr/bin/python
import cv2.cv as cv
from datetime import datetime
import time
import ftplib
import logging

# Import smtplib for the actual sending function
import smtplib

# Here are the email package modules we'll need
from email.mime.image import MIMEImage
from email.mime.multipart import MIMEMultipart

server="127.0.0.1"
user="user"
password="password"
secure=False

email_from = "psaavedra@igaia.com"
email_to="clopez@igalia.com"

log = logging.getLogger()
ch = logging.StreamHandler()
log.addHandler(ch)


def send_email(eventname, filename):
    '''
    Assumes a SMTP server in the localhost

    #XXX: Not yet tested
    '''

    # Create the container (outer) email message.
    msg = MIMEMultipart()
    msg['Subject'] = '[rpicam-alert]: %s' % eventname
    msg['From'] = email_from
    msg['To'] = email_to
    msg.preamble = 'Something is happing in your house!!!'
    fp = open(filename, 'rb')
    img = MIMEImage(fp.read())
    fp.close()
    msg.attach(img)

    # Send the email via our own SMTP server.
    s = smtplib.SMTP('localhost')
    s.sendmail(to, [email], msg.as_string())
    s.quit()


def ftp_upload(server,user,password, filename, secure=False):
    if secure:
        session = ftplib.FTP(server,user,password)
    else:
        session = ftplib.FTP_TLS(server,user,password)
    file = open(filename,'rb')                  # file to send
    session.storbinary('STOR %s' % filename, file)     # send the file
    file.close()                                    # close file and FTP
    session.quit()


class MotionDetectorInstantaneous():
    '''
    threshold
    '''
    
    def onChange(self, val): #callback when the user change the detection threshold
        self.threshold = val
    
    def __init__(self,threshold=8, doRecord=True, showWindows=True,
            uploadVideo=True):
        self.writer = None
        self.font = None
        self.doRecord=doRecord #Either or not record the moving object
        self.show = showWindows #Either or not show the 2 windows
        self.frame = None
        self.upload_video = uploadVideo
    
        self.capture=cv.CaptureFromCAM(0)
        self.frame = cv.QueryFrame(self.capture) #Take a frame to init recorder
       
        self.frame1gray = cv.CreateMat(self.frame.height, self.frame.width, cv.CV_8U) #Gray frame at t-1
        cv.CvtColor(self.frame, self.frame1gray, cv.CV_RGB2GRAY)
        
        #Will hold the thresholded result
        self.res = cv.CreateMat(self.frame.height, self.frame.width, cv.CV_8U)
        
        self.frame2gray = cv.CreateMat(self.frame.height, self.frame.width, cv.CV_8U) #Gray frame at t
        
        self.width = self.frame.width
        self.height = self.frame.height
        self.nb_pixels = self.width * self.height
        self.threshold = threshold
        self.isRecording = False
        self.trigger_time = 0 #Hold timestamp of the last detection
        
        if showWindows:
            cv.NamedWindow("Image")
            cv.CreateTrackbar("Detection treshold: ", "Image", self.threshold, 100, self.onChange)
        
    def initRecorder(self,eventname): #Create the recorder
        codec = cv.CV_FOURCC('M', 'J', 'P', 'G') #('W', 'M', 'V', '2')
        self.writer=cv.CreateVideoWriter(eventname + ".mjpeg", codec, 5, cv.GetSize(self.frame), 1)
        #FPS set to 5 because it seems to be the fps of my cam but should be ajusted to your needs
        self.font = cv.InitFont(cv.CV_FONT_HERSHEY_SIMPLEX, 1, 1, 0, 2, 8) #Creates a font

    def run(self):
        eventname = ""
        started = time.time()
        while True:
            
            curframe = cv.QueryFrame(self.capture)
            instant = time.time() #Get timestamp o the frame
            
            self.processImage(curframe) #Process the image
            
            if not self.isRecording:
                if self.somethingHasMoved():
                    eventname = datetime.now().strftime("%b-%d_%H_%M_%S")
                    self.trigger_time = instant #Update the trigger_time
                    if instant > started +5:#Wait 5 second after the webcam start for luminosity adjusting etc..
                        print datetime.now().strftime("%b %d, %H:%M:%S"), "Something is moving !"
                        if self.doRecord: #set isRecording=True only if we record a video
                            self.isRecording = True
                            self.initRecorder(eventname)
                        cv.SaveImage(eventname + ".jpg", self.frame)     # save frame as JPEG file
                        try:
                            send_email(eventname, eventname + ".jpg")
                        except Exception, e:
                            log.error("Problem sending the email alert: %s" % e)
            else:
                if instant >= self.trigger_time + 10: #Record during 10 seconds
                    print datetime.now().strftime("%b %d, %H:%M:%S"), "Stop recording"
                    self.isRecording = False
                    if self.upload_video:
                        try:
                            ftp_upload(server,user,password, eventname + ".mjpeg", secure=False)
                        except Exception, e:
                            log.error("Problem uploading video to FTP: %s" % e)
                else:
                    cv.PutText(curframe,datetime.now().strftime("%b %d, %H:%M:%S"), (25,30),self.font, 0) #Put date on the frame
                    cv.WriteFrame(self.writer, curframe) #Write the frame
            
            if self.show:
                cv.ShowImage("Image", curframe)
                cv.ShowImage("Res", self.res)
                
            cv.Copy(self.frame2gray, self.frame1gray)
            c=cv.WaitKey(1) % 0x100
            if c==27 or c == 10: #Break if user enters 'Esc'.
                break            
    
    def processImage(self, frame):
        cv.CvtColor(frame, self.frame2gray, cv.CV_RGB2GRAY)
        
        #Absdiff to get the difference between to the frames
        cv.AbsDiff(self.frame1gray, self.frame2gray, self.res)
        
        #Remove the noise and do the threshold
        cv.Smooth(self.res, self.res, cv.CV_BLUR, 5,5)
        cv.MorphologyEx(self.res, self.res, None, None, cv.CV_MOP_OPEN)
        cv.MorphologyEx(self.res, self.res, None, None, cv.CV_MOP_CLOSE)
        cv.Threshold(self.res, self.res, 10, 255, cv.CV_THRESH_BINARY_INV)

    def somethingHasMoved(self):
        nb=0 #Will hold the number of black pixels

        for x in range(self.height): #Iterate the hole image
            for y in range(self.width):
                if self.res[x,y] == 0.0: #If the pixel is black keep it
                    nb += 1
        avg = (nb*100.0)/self.nb_pixels #Calculate the average of black pixel in the image

        if avg > self.threshold:#If over the ceiling trigger the alarm
            return True
        else:
            return False
        
if __name__=="__main__":
    detect = MotionDetectorInstantaneous(threshold=8, doRecord=True,
                                         showWindows=False, uploadVideo=True)
    detect.run()
